name: cod-atlas

services:
  cod-atlas:
    image: cod-atlas:local
    container_name: cod-atlas
    hostname: cod-atlas
    build:
      context: .
    ports:
      - "${COD_ATLAS_PORT:-8080}:80"
    networks:
      - cod-atlas-network
    volumes: []

networks:
  cod-atlas-network:
    name: cod-atlas-network
    driver: bridge
