services:
  cod-atlas:
    # Built by GitHub Actions and pulled from GHCR.
    image: ghcr.io/time-wasters/cod-atlas:staging

    networks:
      - proxy-network

    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  proxy-network:
    external: true
    name: proxy-network