services:
  cod-atlas:
    # Built by GitHub Actions and pulled from GHCR
    image: ghcr.io/time-wasters/cod-atlas:staging

    ports:
      - "8080:80"

    networks:
      - cod-atlas-staging-network

    deploy:
      replicas: 1

      restart_policy:
        condition: any

networks:
  cod-atlas-staging-network:
    name: cod-atlas-staging-network
    driver: overlay