import type { LevelAppearanceDto } from "./level-appearance.dto.js";
import type { LevelVerificationDto } from "./level-verification.dto.js";

export type AtlasEntryDto = {
  id: string;
  levelId: string;
  locationId: string;
  primary: boolean;
  title: string;
  game: string;
  gameIds: string[];
  campaign?: LevelAppearanceDto["campaign"];
  campaignOrder?: number;
  contentUpdate?: LevelAppearanceDto["contentUpdate"];
  wiki: string;
  wikiArticle: string;
  verified?: LevelVerificationDto;
  country: string;
  region?: string | null;
  city?: string | null;
  landmark?: string | null;
  coordinates?: [number, number] | null;
  precision: "exact" | "approximate" | "city" | "region" | "country" | "off-world";
  confidence?: "high" | "medium" | "fallback";
  method?: string;
  urls?: Partial<Record<"googleMaps" | "wikipedia" | "callOfDutyMaps", string>>[];
  hasLevelNotes: boolean;
  modes: ("singleplayer" | "multiplayer" | "zombies")[];
  appearances: LevelAppearanceDto[];
};
